### ISSUE TITLE
Single-click on notification area icon does not bring up contact list

### ISSUE THREAD

**Issue by marczellm** [xmikos/qhangups#1]
Single-clicking on the notification area icon does not bring up the contact list for me. I'm on Windows 7.

**Comment by xmikos** [comment]
Single click brings contact list only if you are already connected to Hangouts server. There seems to be now some deeper issue that on_connect method is never called. I am looking into it...

**Comment by AndrewJDR** [comment]
Also fixed for me after ff4d4dd6146a144646f17f5503607f784bd9a1af

**Comment by xmikos** [comment]
It's fixed, after latest update you can open conversations list window (with single-click on systray icon) even if you are not yet connected to server. Closing...
