### ISSUE TITLE
Improve pip install

### ISSUE THREAD

**Issue by marczellm** [xmikos/qhangups#10]
When I want to `pip install qhangups`, the dependencies such as `hangups` don't get installed. (If I `pip install hangups`, it installs all of `hangups`' dependencies for example.) I recommend improving `qhangups`' `setup.py`, to maybe use `setuptools` instead of `distutils` and specify the needed version of dependencies in it etc.

**Comment by xmikos** [comment]
I have made complete switch to `setuptools`. Everything should now work as expected, but `PyQt4` must be still installed manually. PyQt is incompatible with setuptools/pip and even if you manually install system-wide PyQt, setuptools doesn't find it and throw error. So I have removed PyQt4 from _install_requires_ field in _setup.py_ to resolve this.
