### ISSUE TITLE
browser window empty [mac os ]

### ISSUE THREAD

**Issue by hovancik** [xmikos/qhangups#11]
when I run `qhangups` i am not presented browser window. 

When I click Settings, I am able to see the window, but it's empty. Right click and Refresh not doing anything.

Console not saying anything. 

pyqt/4.11.3
python/3.4.3

**Comment by xmikos** [comment]
I don't have Mac OS X to test it (I am developing QHangups primarily for Linux and test it from time to time on Windows), but it should work. Which window is empty? After you start QHangups, you should only see icon in system tray (I _think_ in dock on Mac OS X, but I am not sure). After single click on this icon, you should be presented with empty conversations list window. If you double click on the same icon (or right click and select _Connect_ from menu), you should be connected to Hangouts server and this window will be filled with list of active Hangouts conversations.

First time you click on _Connect_ you should be presented with simple browser window with Google login (where you fill your credentials and copy resulting OAuth token). Is this the window which is empty for you? Everything other seems right?

**Comment by hovancik** [comment]
![screen shot 2015-06-16 at 09 00 49](https://cloud.githubusercontent.com/assets/4745859/8177588/71e4a51c-1406-11e5-9ddd-d95f8adb9350.png)

It's as you said, but as you can see, browser window is empty. Not sure how to continue.

**Comment by xmikos** [comment]
Now that is strange... There is no error in console window (if you started it from console)? The only thing I can think of is that your Qt/PyQt installation is somehow broken (missing QtWebKit module or something like that... but you should definitely see error in console window if that would be the case).

**Comment by xmikos** [comment]
You can try to install PyQt5 and use PyQt5 branch of QHangups (it's work in progress, but it should work): https://github.com/xmikos/qhangups/tree/pyqt5

If there would be same problem even in PyQt5, something different is going on...

**Comment by hovancik** [comment]
```
qhangups
Language changed
2015-06-16 09:16:20.657 Python[97506:5717118] -[NSApplication runModalSession:]: Use of freed session detected. Do not call runModalSession: after calling endModalSesion:.
QThread: Destroyed while thread is still running
```

That's all I see in console. Last 2 lines are when closing app.

**Comment by xmikos** [comment]
That's OK... can you try PyQt5 branch?

**Comment by hovancik** [comment]
Yes, but not sure how to do it. I am not familiar with Python. The version I have I've installed with pip3.

**Comment by xmikos** [comment]
Just install PyQt5 (`brew install pyqt5`), other Python dependencies are same as for PyQt4 version, so you should have them already installed. Then clone this repository, checkout `pyqt5` branch and run it:

```
git clone https://github.com/xmikos/qhangups.git
cd qhangups
git checkout pyqt5
python -m qhangups
```

**Comment by hovancik** [comment]
It's the same.  

How can I enable debug in webkit? Maybe I will be able to see something in that browser window when looking at source of page shown

**Comment by xmikos** [comment]
Well, you can first try simple browser window. Download this file: https://gist.github.com/xmikos/53363482e0e5f490c3f4

Copy it to your cloned PyQt5 branch of QHangups (to `qhangups` subdirectory, same location where is `__main__.py` file). Then run it with `python -m qhangups.browser_test`. If it works, you should be presented with Google Search page.

**Comment by xmikos** [comment]
You can also replace `browser.py` in the same directory with this one: https://gist.github.com/xmikos/8554cf42522e739a6d0d

Now it should print source of loaded web page to console, so you can see what it really loads.

**Comment by hovancik** [comment]
```
Loading URL: https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=xxxx&client_id=xxxxx&scope=xxxxx
Load finished: False
Source:
<html><head></head><body></body></html>
```

maybe you could use default system browser to open the link instead of making browser window? when I copied the link to browser and copied the code, I was able to login

**Comment by xmikos** [comment]
I can open it in external browser, but it shouldn't be needed. And I plan in future to automate this task, so manually copying auth token wouldn't be needed anymore (which can be only done in native app browser window). It works without problems in Linux and Windows, I would be really glad to fix this issue also in Mac OS X. Are you open to assist me with this task a little more?

**Comment by hovancik** [comment]
Yeah, sure. Let me know what I need to try.

**Comment by xmikos** [comment]
Have you tried that simple `browser_test.py`? Did it work or not?

**Comment by hovancik** [comment]
```
 python3 -m qhangups.browser_test
/usr/local/opt/python3/bin/python3.4: No module named qhangups.browser_test
```

**Comment by xmikos** [comment]
You have to be in the cloned main `qhangups` directory. Then it should work.

**Comment by hovancik** [comment]
My bad, I was saving the file from Firefox and I saved it in wrong dir. 
Anyway, it works now (Google search address).

**Comment by xmikos** [comment]
So the problem is only with that auth URL (`https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=xxxx&client_id=xxxxx&scope=xxxxx`)? Really strange, I am out of ideas now. Could you change URL in `browser_test.py` from `http://www.google.com` to `http://eutopia.cz/request.php` and paste the result here?

**Comment by xmikos** [comment]
And then try `https://eutopia.cz/request.php` (HTTPS instead of HTTP).

**Comment by hovancik** [comment]
```
Array
(
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [PHPRC] => /etc/php5/cgi
    [PHP_FCGI_MAX_REQUESTS] => 1000
    [CONTENT_LENGTH] => 0
    [SCRIPT_NAME] => /request.php
    [REQUEST_URI] => /request.php
    [QUERY_STRING] => 
    [REQUEST_METHOD] => GET
    [SERVER_PROTOCOL] => HTTP/1.1
    [GATEWAY_INTERFACE] => CGI/1.1
    [REMOTE_PORT] => 52506
    [SCRIPT_FILENAME] => /var/www/default/request.php
    [SERVER_ADMIN] => webmaster@eutopia.cz
    [CONTEXT_DOCUMENT_ROOT] => /var/www/default
    [CONTEXT_PREFIX] => 
    [REQUEST_SCHEME] => http
    [DOCUMENT_ROOT] => /var/www/default
    [REMOTE_ADDR] => 88.208.91.78
    [SERVER_PORT] => 80
    [SERVER_ADDR] => 31.31.73.191
    [SERVER_NAME] => eutopia.cz
    [SERVER_SOFTWARE] => Apache/2.4.10 (Debian)
    [SERVER_SIGNATURE] => 
Apache/2.4.10 (Debian) Server at eutopia.cz Port 80


    [HTTP_HOST] => eutopia.cz
    [HTTP_ACCEPT_LANGUAGE] => en-US,*
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_CONNECTION] => close
    [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) Python Safari/538.1
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /request.php
    [REQUEST_TIME_FLOAT] => 1434460175.3953
    [REQUEST_TIME] => 1434460175
)
```

http

**Comment by hovancik** [comment]
```
Array
(
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [PHPRC] => /etc/php5/cgi
    [PHP_FCGI_MAX_REQUESTS] => 1000
    [CONTENT_LENGTH] => 0
    [SCRIPT_NAME] => /request.php
    [REQUEST_URI] => /request.php
    [QUERY_STRING] => 
    [REQUEST_METHOD] => GET
    [SERVER_PROTOCOL] => HTTP/1.1
    [GATEWAY_INTERFACE] => CGI/1.1
    [REMOTE_PORT] => 52573
    [SCRIPT_FILENAME] => /var/www/default/request.php
    [SERVER_ADMIN] => webmaster@eutopia.cz
    [CONTEXT_DOCUMENT_ROOT] => /var/www/default
    [CONTEXT_PREFIX] => 
    [REQUEST_SCHEME] => https
    [DOCUMENT_ROOT] => /var/www/default
    [REMOTE_ADDR] => 88.208.91.78
    [SERVER_PORT] => 443
    [SERVER_ADDR] => 31.31.73.191
    [SERVER_NAME] => eutopia.cz
    [SERVER_SOFTWARE] => Apache/2.4.10 (Debian)
    [SERVER_SIGNATURE] => 
Apache/2.4.10 (Debian) Server at eutopia.cz Port 443


    [HTTP_HOST] => eutopia.cz
    [HTTP_ACCEPT_LANGUAGE] => en-US,*
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_CONNECTION] => close
    [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) Python Safari/538.1
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [SSL_TLS_SNI] => eutopia.cz
    [HTTPS] => on
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /request.php
    [REQUEST_TIME_FLOAT] => 1434460249.631
    [REQUEST_TIME] => 1434460249
)
```

https

**Comment by xmikos** [comment]
Thanks... can you now please replace `browser.py` with this one: https://gist.github.com/xmikos/73ae4f4d7d2f28c1f7b7

Then delete `refresh_token.txt` file (it will be somewhere in application-specific configuration directory, I don't know where is it on Mac OS X, but it should be named `QHangups` or possibly `qhangups.eutopia.cz`) and start QHangups again (from your PyQt5 clone).

**Comment by hovancik** [comment]
same ;/ 

```
qhangupspyqt5$ python3 -m qhangups
Language changed
Loading URL: https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=xxx&client_id=xxxx
Load finished: False
Source:
<html><head></head><body></body></html>
```

**Comment by xmikos** [comment]
I am really out of ideas now :-( Is there some way how one can test application on Mac OS X (other than purchasing Mac)? Remote desktop, image in VirtualBox or something?

**Comment by xmikos** [comment]
I have tried it in Mac OS X 10.10 Yosemite (don't ask how ;-)) and it works for me without problems. How did you installed PyQt? I have proceeded like this:

```
brew install pyqt --with-python3
pip3 install qhangups
qhangups
```

**Comment by hovancik** [comment]
Well, no idea, I myself have mac very short time. Would be best to see if someone else with mac has same issue

**Comment by hovancik** [comment]
I proceeded the same. The problem might be that first I was trying to install with python2, and after some errors I figured out I need python3

**Comment by xmikos** [comment]
I don't know how exactly `brew` works, so maybe it is the issue, maybe not. Could you somehow try to completely uninstall pyqt and pyqt5 (and other packages installed by brew) and then try this process again?

**Comment by hovancik** [comment]
Yeah, I will try to do that. Might take few days (or not). Anyway, I will try to remember to report back.

**Comment by hovancik** [comment]
So I tried, it's the same. I guess I can close the issue.
