### ISSUE TITLE
Windows: does nothing on startup

### ISSUE THREAD

**Issue by WACOMalt** [xmikos/qhangups#13]
after installing all dependencies and installing, running qhangups does nothing. no window pops up. no error. It accepts the command and nothing happens.

adding --help or -d for debug also does nothing. gives no output.

**Comment by marczellm** [comment]
In some cases, qhangups does not find the icon for some reason, and adds an invisible icon to the notification area, but the empty space there can still be single-clicked to bring up the window, double-clicked to connect or right-clicked to bring up the menu.

**Comment by xmikos** [comment]
I have now tested latest QHangups v1.7.0 on Windows 8.1 and it works without problems, do you still have this issue?

**Comment by marczellm** [comment]
With 1.7 the icon appears now as expected.
