### ISSUE TITLE
plans for Qt5/PyQt5?

### ISSUE THREAD

**Issue by ahjolinna** [xmikos/qhangups#16]
do u have any plans to port this app to Qt5?, what I understand is that PyQt5 is almost completely different from PyQt4, so maybe it easier to rewrite it than port?

**Comment by xmikos** [comment]
Yes, I have already created pyqt5 branch and ported QHangups, but didn't have time recently to complete it. You can try it.

**Comment by xmikos** [comment]
And no, Qt5 isn't too much different, only minor changes, look at diff

**Comment by xmikos** [comment]
I have merged `pyqt5` branch into master. New QHangups version 1.7.0 is PyQt 5 only.
