### ISSUE TITLE
QHangups doesn't work on Windows because SSL is not supported with ProactorEventLoop

### ISSUE THREAD

**Issue by BramBonne** [xmikos/qhangups#2]
When starting qhangups (installed from https://aur.archlinux.org/packages/qhangups/) for the first time, it hangs with only the message `Language changed` being displayed.

Running qhangups with the -d (debug) switch provides the following log output:

> 2015-02-26 16:45:31,908 - quamash.QEventLoop - DEBUG - Adding reader callback for file descriptor 12
> 2015-02-26 16:45:31,914 - quamash.QEventLoop - DEBUG - Starting Qt event loop

**Comment by xmikos** [comment]
It doesn't hang, if you right click on system tray icon, you should see menu and it should react, is that the case? But there is another problem that on_connect method isn't called (so you never see contact list and messages). I am looking into it, stay tuned...

**Comment by BramBonne** [comment]
Oops, I was expecting a main window of some sorts. Having Ctrl-C not work when the app was started made me suspect that it was hanging.

Logging in with a Google app-specific password does not seem to work, however.

**Comment by xmikos** [comment]
Yeah, now it's deeply broken. I don't know yet what caused it, but I suspect some change in quamash, aiohttp or hangups themselves. Quamash/PyQt event loop runs, but it seems that hangups coroutines aren't...

**Comment by AndrewJDR** [comment]
This is fixed for me after updating to ff4d4dd6146a144646f17f5503607f784bd9a1af

**Comment by xmikos** [comment]
Should be fixed in new version, closing

**Comment by marczellm** [comment]
It still never connects for me.

**Comment by xmikos** [comment]
marczellm: Are you sure you have latest revision from Git? And also latest Hangups and Quamash from Git.

**Comment by marczellm** [comment]
Yes

**Comment by xmikos** [comment]
Ok, then first try console version of Hangups. If even that doesn't work, there would be some problem with your Google account I think. If console version of Hangups works, delete `~/.local/share/QHangups/` directory, start `qhangups --debug`, log in and send me your `~/.local/share/QHangups/hangups.log` file (put it on https://gist.github.com preferably).

**Comment by marczellm** [comment]
Gist at https://gist.github.com/marczellm/b2a32e8a40adebe417a7

I seriously suspect that it has to do something with me being on Windows. The console version of Hangups doesn't even work on Windows because of `urwid` importing `fcntl`.

**Comment by xmikos** [comment]
Unfortunately you are right right. You can see this in log:

```
File "D:\Python34\lib\asyncio\base_events.py", line 186, in _make_ssl_transport
  raise NotImplementedError
```

And according to Python documentation (https://docs.python.org/3/library/asyncio-eventloops.html#windows), SSL is not supported with ProactorEventLoop (which is used by asyncio on Windows). You can also use SelectorEventLoop on Windows, but it has some other serious limitations there (which is why ProactorEventLoop is chosen by Quamash on Windows by default). I don't know if Quamash can work with SelectorEventLoop on Windows, if not I can't do anything about it. But I will try it and let you know.

**Comment by xmikos** [comment]
Ok, I have found this Python patch: http://bugs.python.org/issue22560 (New SSL implementation based on ssl.MemoryBIO). It should add support for SSL with ProactorEventLoop on Windows and it seems that it has been merged into Python 3.5. Can you try pre-release Python 3.5.0a2 (https://www.python.org/downloads/release/python-350a2/) if it will work with it?

**Comment by xmikos** [comment]
It seems to be really in there: https://github.com/python/cpython/blob/master/Lib/asyncio/proactor_events.py#L385

Please try it and let me know...

**Comment by marczellm** [comment]
Thank you for the pointers. However building and installing dependencies on Windows requires much more effort. As the Python 3.5 release is scheduled for September, there are no prebuilt PyQt binaries for 3.5 yet, also when installing modules with C code, pip requires Visual C++ 14.0 which isn't even released yet, etc. etc. I'm perfectly happy with postponing this until September if you are.

**Comment by xmikos** [comment]
I have tried Quamash with SelectorEventLoop on Windows and QHangups works! So you can use it even before Python 3.5 would be released. I have merged this workaround in, so latest Git revision of QHangups should work for you. Please try it and let me know...

I am closing it now, but if you stomp on some problem, I will reopen it again.
