### ISSUE TITLE
The login thing won't popup

### ISSUE THREAD

**Issue by Kommynct** [xmikos/qhangups#20]
A way to force it would be nice, because all that I have is a thing that says "disconnected"

And i know if the login thing would popup, everything would work, because i currently have regular hangups working.

I'm running linux if that's vaguely useful, specifically arch.

**Comment by thecodrr** [comment]
Just right click on the `qhangups` icon on the notification bar and select `Connect`. The login window will popup.

**Comment by Kommynct** [comment]
I did that forever ago, but that was not working at the time either, i remember trying that in particular.

I no longer have the config to test this though, so this issue should be closed.

**Comment by thecodrr** [comment]
Well then, click the close issue button.
