### ISSUE TITLE
invalid_scope on authorisation

### ISSUE THREAD

**Issue by MartijnBraam** [xmikos/qhangups#29]
I've just installed qhangups but the login page is invalid.

![screenshot from 2016-09-09 13-16-14](https://cloud.githubusercontent.com/assets/6928199/18385228/a3a6cb06-768f-11e6-84f4-11dc98e1420e.png)

As text:
1. That’s an error.

Error: invalid_scope

Not authorized to request the scopes: [https://www.google.com/accounts/OAuthLogin]

Learn more

Request Details
scope=https://www.google.com/accounts/OAuthLogin
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=936475272427.apps.googleusercontent.com

**Comment by xmikos** [comment]
Unfortunately Google recently broke auth method that is used by Hangups (library that QHangups uses). See this issue: [#260](https://github.com/tdryer/hangups/issues/260)

I can't do anything with it until this issue is fixed...

**Comment by xmikos** [comment]
All other third-party Hangouts clients have same problem right now. Existing auth tokens (if you have logged in before change made by Google) should still work, but you can't get new one.

**Comment by dequis** [comment]
I wrote a workaround here, a manual way to get oauth tokens https://github.com/tdryer/hangups/issues/260#issuecomment-246578670

Since it seems you use a webview, [what i said in the yakyak tracker](https://github.com/yakyak/yakyak/issues/358#issuecomment-246582907) probably also applies to this project:

> Given how yakyak uses electron and can load full web pages, it may be possible to integrate this the way it was intended to - in a webview, with something outside of the frame grabbing the cookie just like the iOS app does.
> 
> So you're lucky there, but for the rest of the hangups users we still have to find something better.

**Comment by izenja** [comment]
hangups currently works again, but qhangups doesn't run in the current state. It seems like it would be a good time to update it to work again, since hangups has had the token update.

**Comment by xmikos** [comment]
It's fixed in new version 1.8.1
