### ISSUE TITLE
Can't change font of conversations window

### ISSUE THREAD

**Issue by jpwgarrison** [xmikos/qhangups#7]
I am able to change the font of the main window and menus/popups, but text in conversations is very small. I tried multiple DEs and settings(font and DPI).

**Comment by xmikos** [comment]
I am setting font in CSS to: `font-family: sans-serif; font-size: 10pt;`

Is 10pt really that small for you? It is default font size in various desktop environments, maybe your DPI setting is not right?

Anyway you can find it (and change it) in `conversationwidget.py` file, it is in `init_messages` method. It would be great if I can somehow force QWebView to use default system (Qt) font settings, but I didn't find a way how to do it yet...

**Comment by jpwgarrison** [comment]
That works great, thanks! My job issued me a 4k monitor a couple of weeks ago and I have spent an amusing amount of time increasing font sizes all over. 18-24pt mostly!

**Comment by xmikos** [comment]
Are you sure you have right DPI in X server? If I am not mistaken, 10pt font should have same real size  independent on resolution (if you have your DPI set right).
